<?php
// Set page title.
$this->headTitle($this->translate('Search Home'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

// Set default value if necessary:
if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
}

$this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent">
    <?php $this->slot('search-home-hero')->start() ?>
    <?= $this->context($this)->renderInContext('search/searchbox.phtml', ['ignoreHiddenFilterMemory' => true]) ?>
    <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
    <?= $this->slot('search-home-hero')->end() ?>
</div>
<div class="homeContent">
    <h3>Using Library Catalogue Plus</h3>
    <p>Choose the correct search tab for you:</p>
    <ul><strong>Catalogue</strong> for books, journal titles, DVDs and other material held by the Library and all items from the Loughborough University Research Repository.</ul>
    <ul><strong>Articles Plus</strong> for details and access to <a href="https://internal.lboro.ac.uk/info/library/uniwide/primocentral/">online full-text journal articles and conference papers</a> accessible at Loughborough University.</ul>
    <p>Login to manage your Library account, including renewing loans.</p>
</div>

<?= implode('', array_map([$this, 'contentBlock'], $blocks ?? [])) ?>
