<?php
// Set page title.
$this->headTitle($this->translate('Search Home'));

// Disable top search box -- this page has a special layout.
$this->layout()->searchbox = false;

// Set default value if necessary:
if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
}

$this->layout()->breadcrumbs = false;
?>

<div class="searchHomeContent">
    <?php $this->slot('search-home-hero')->start() ?>
    <?= $this->context($this)->renderInContext('search/searchbox.phtml', ['ignoreHiddenFilterMemory' => true]) ?>
    <?= $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
    <?= $this->slot('search-home-hero')->end() ?>
</div>
<div class="homeContent">
    <h2>Using Library Catalogue Plus</h2>
    <p>Choose the correct search tab for you:</p>
    <ul>
        <li><strong>Catalogue</strong> for books, ebooks, journal titles, audiovisual and other material held by the Library, plus all items from the Loughborough University Research Repository.</li>
        <li><strong>Articles Plus</strong> for details and access to <a href="https://internal.lboro.ac.uk/info/library/uniwide/primocentral/">online full-text journal articles and conference papers</a> accessible via Loughborough University.</li>
    </ul>
    <p><a href="/MyResearch/UserLogin">Log in</a> to review your Library account, including current loans, loan history, hold requests and saved searches.</p>
    <p><strong>Need help?</strong> <a href="https://www.lboro.ac.uk/services/library/contact/" target="_blank">Contact the Library.</a></p>
</div>


<hr />

<?= implode('', array_map([$this, 'contentBlock'], $blocks ?? [])) ?>
