<?php
  $holdingVisible = $this->holdings()->holdingIsVisible($holding);
  $statusDescription = strtolower($holding['availability']->getStatusDescription() ?? '');
  if (
    ( $this->holdings()->holdingIsVisible($holding) ) &&
    ( $statusDescription != 'withdrawn' ) &&
    ( $statusDescription != 'missing' ) &&
    ( $statusDescription != 'missing from bundle' ) &&
    ( $statusDescription != 'paid for' ) &&
    ( $statusDescription != 'repair shelf' ) &&
    ( $statusDescription != 'cancelled' )
  ):
?>
  <?php
    $check = $holding['check'] ?? false;
    $checkStorageRetrievalRequest = $holding['checkStorageRetrievalRequest'] ?? false;
    $checkILLRequest = $holding['checkILLRequest'] ?? false;
    $availabilityStatus = $holding['availability'];
  ?>
  <tr class="holding-row"<?=$this->schemaOrg()->getAttributes(['vocab' => 'http://schema.org/', 'typeof' => 'Offer'])?>>
    <td colspan="2" class="holding-<?=$availabilityStatus->isAvailable() ? 'available' : 'unavailable' ?>">
      <div class="holding-details">
        <span class="holding-field copy-number">
          <?=$this->transEsc('Copy')?> <?=$this->escapeHtml($holding['number'])?>[<?=$this->escapeHtml($holding['barcode'] ?? 'Unknown')?>]
        </span>
        <span class="holding-field shelving_loc">
          <?php if($holding['shelving_loc'] ?? false): ?>
            <?=$this->escapeHtml($holding['shelving_loc'])?>
          <?php else: ?>
            <em>Unknown</em>
          <?php endif; ?>
        </span>
        <span class="holding-field availability text-end">
          <?php if ($holding['reserve'] == 'Y'): ?>
            <?=$this->schemaOrg()->getLink('http://schema.org/InStoreOnly', 'availability')?>
            <?=$this->transEsc('On Reserve - Ask at Circulation Desk')?><br>
          <?php endif; ?>

          <?php
            $statusClass = $this->availabilityStatus()->getClass($availabilityStatus);
            $statusDescription = $availabilityStatus->getStatusDescription();
            $schemaAvailabilityUri = $availabilityStatus->getSchemaAvailabilityUri();
          ?>
          <span class="<?=$this->escapeHtmlAttr($statusClass)?>">
            <?=$this->transEsc($statusDescription)?>
            <?php if ($schemaAvailabilityUri): ?>
              <?=$this->schemaOrg()->getLink($schemaAvailabilityUri, 'availability')?>
            <?php endif; ?>
          </span>
          <?php if (!$availabilityStatus->isAvailable()): ?>
            <?php if ($holding['returnDate'] ?? false): ?>
              <span class="small return-date"><?=$this->escapeHtml($holding['returnDate'])?></span>
            <?php endif; ?>
            <?php if ($holding['duedate'] ?? false): ?>
              <span class="small due-date"><?=$this->transEsc('Due')?>: <?=$this->escapeHtml($holding['duedate'])?></span>
            <?php endif; ?>
            <?php if (($holding['requests_placed'] ?? 0) > 0): ?>
              <span class="request-count"><?=$this->transEsc('Requests')?>: <?=$this->escapeHtml($holding['requests_placed'])?></span>
            <?php endif; ?>
          <?php endif; ?>
        </span>
      </div>

      <?php if (isset($holding['item_notes'])): ?>
        <div class="holding-notes">
          <div class="item-notes">
            <b><?=$this->transEsc('Item Notes')?>:</b>
            <ul>
              <?php foreach ($holding['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
      <?php endif; ?>
      <?php if (!empty($holding['bound_with_records'])): ?>
        <?=
          $this->render(
              'RecordTab/holdingsils/boundwith.phtml',
              [
                'boundWithRecords' => $holding['bound_with_records'],
                'callNumber' => $holding['callnumber'],
                'callNumberCount' => count($callNos),
                'driver' => $driver,
              ]
          );
        ?>
      <?php endif; ?>
      <?php /* Embed item structured data: library, barcode, call number */ ?>
      <?php if ($holding['location'] ?? false): ?>
        <?=$this->schemaOrg()->getMeta('seller', $holding['location'])?>
      <?php endif; ?>
      <?php if ($holding['barcode'] ?? false): ?>
        <?=$this->schemaOrg()->getMeta('serialNumber', $holding['barcode'])?>
      <?php endif; ?>
      <?php if ($holding['callnumber'] ?? false): ?>
        <?=$this->schemaOrg()->getMeta('sku', $holding['callnumber'])?>
      <?php endif; ?>
      <?php /* Declare that the item is to be borrowed, not for sale */ ?>
      <?=$this->schemaOrg()->getLink('http://purl.org/goodrelations/v1#LeaseOut', 'businessFunction')?>
      <?=$this->schemaOrg()->getLink('#record', 'itemOffered')?>
    </td>
  </tr>
<?php endif; ?>
